### ISSUE TITLE
running fetchcord as .service is failing to get terminal info

### ISSUE THREAD

**Issue by nekoize** [MrPotatoBobx/FetchCord#108]
# Debug info

```
----out.py----

----DE/WM----
deid: N/A
wmid: N/A
wmline item 0: ['WM: N/A']

----TERMINAL----

fontline: ['Font: N/A']
termid: N/A
termline item 0: Terminal: N/A
themeline: Theme: N/A

----HOST INFO----

hostline: Host: N/A
batteryline: Battery: N/A
resline: Resolution: N/A

----GPU INFO----

gpuinfo: GPU: N/A
gpuvendor: N/A

----CPU INFO----

cpuvendor: N/A
cpumodel: N/A
cpuinfo: CPU: N/A
cpuline item 0: ['CPU: N/A']
memline: Memory: N/A

----OS INFO----

sysosline: OS: N/A
sysosid: N/A
diskline: Disk: N/A
packagesline item 0: Packages: N/A
Unknown GPU, contact us on github to resolve this.
Unknown DE/WM, contact us on github to resolve this.
Unknown shell, contact us on github to resolve this.
Unknown Host, contact us on github to resolve this.(Keyerror)
Unsupported Terminal. contact us on github to resolve this.(Keyerror)
Unsupported Distro, contact us on the GitHub page to resolve this.(keyerror)

----testing.py----
----DE/WM----

deid: N/A
wmid: N/A

----TERMINAL/SHELL----

termid: N/A
shellid: unknown

----HOST INFO----

hostid: o

----GPU INFO----

gpuvendor: N/A

----CPU INFO----

cpumodel: N/A
```

basically fetchcord as a .service is trying to get the terminal its running on (systemd)
it cannot display it so you put this handy thing that fixes that, it doesnt.
```
setting custom time 15 seconds
Custom terminal font not set because a terminal font already exists, ['Terminal Font: Iosevka 15.0 ']
Traceback (most recent call last):
  File "/home/wael/.local/bin/fetchcord", line 5, in <module>
    from fetch_cord.run_rpc import main
  File "/home/wael/.local/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 11, in <module>
    from fetch_cord.testing import gpuid, cpuappid, appid, desktopid, termappid, hostappid, shellid, moboid
  File "/home/wael/.local/lib/python3.8/site-packages/fetch_cord/testing.py", line 119, in <module>
    termline[0] = "Terminal: %s" % args.terminal
TypeError: 'str' object does not support item assignment
```
this will repeat several times.

**Comment by BlivionIaG** [comment]
Hello, testing.py won't exists anymore,  but i'll need to check that on 2.7

**Comment by Wael2727** [comment]
since this was 21 DAYS ago i will now test it if it still works

**Comment by BlivionIaG** [comment]
Yeah, sorry for the delay, i'm currently the only person active at the time on the project, i made a new architecture on branch 2.7 and now i'm trying to close the issues :)

**Comment by MrPotatoBobx** [comment]
does it work yet?

**Comment by MrPotatoBobx** [comment]
I will close the issue now, reopen if it still occurs
