### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by rdlmda** [MrPotatoBobx/FetchCord#113]
# Debug info

```
GPU: NVIDIA GeForce GT 740M bash: nvidia-smi: comando não encontrado
----out.py----

----DE/WM----
deid: GNOME
wmid: Mutter
wmline item 0: ['WM: Mutter ']

----TERMINAL----

fontline: ['Font: N/A']
termid: gnome-terminal
termline item 0: Terminal: gnome-terminal 
themeline: WM Theme: Adwaita Theme: Adwaita [GTK2/3] 

----HOST INFO----

hostline: Host: Inspiron 5437 
batteryline: Battery: N/A
resline: Resolution: 1366x768, 1366x768 

----GPU INFO----

gpuinfo: 
GPU: NVIDIA GeForce GT 740M bash: nvidia-smi: comando não encontrado
gpuvendor: IntelNVIDIA

----CPU INFO----

cpuvendor: Intel
cpumodel: Intel i5
cpuinfo: CPU: Intel i5-4200U  @ 2.600GHz 
cpuline item 0: ['CPU: Intel i5-4200U (4) @ 2.600GHz ']
memline: Memory: 5130MiB / 15910MiB 

----OS INFO----

sysosline: OS: Fedora release 32 (Thirty Two) x86_64 
sysosid: Fedora
diskline: Disk: N/A
packagesline item 0: Packages: 2758 (rpm) 

----testing.py----
----DE/WM----

deid: GNOME
wmid: Mutter

----TERMINAL/SHELL----

termid: gnome-terminal
shellid: bash

----HOST INFO----

hostid: Inspiron

----GPU INFO----

gpuvendor: IntelNVIDIA

----CPU INFO----

cpumodel: Intel i5

Connecting
----run_rpc----

uptime in epoch: 1606169467.0
cpuid: 740485660703719464
cpuappid: 741099939198926920
termappid: 741328861115056160
hostappid: 743970870631858288
Packages: 2758 (rpm) 
('DEFAULT', <Section: DEFAULT>)
('cycle_0', <Section: cycle_0>)
('cycle_1', <Section: cycle_1>)
('cycle_2', <Section: cycle_2>)
('cycle_3', <Section: cycle_3>)
Traceback (most recent call last):
  File "/home/ruda/.local/bin/fetchcord", line 8, in <module>
    sys.exit(main())
  File "/home/ruda/.local/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 39, in main
    loonix(config, loop, gpuinfo, memline, cpuinfo,
  File "/home/ruda/.local/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 421, in loonix
    first_connect()
  File "/home/ruda/.local/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 47, in first_connect
    RPC.connect()
  File "/home/ruda/.local/lib/python3.8/site-packages/pypresence/presence.py", line 41, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ruda/.local/lib/python3.8/site-packages/pypresence/baseclient.py", line 121, in handshake
    self.sock_reader, self.sock_writer = await asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
  File "/usr/lib64/python3.8/asyncio/streams.py", line 111, in open_unix_connection
    transport, _ = await loop.create_unix_connection(
  File "/usr/lib64/python3.8/asyncio/unix_events.py", line 244, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/lib64/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/lib64/python3.8/asyncio/selector_events.py", line 501, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
```

**If you are unable to run FetchCord please run `neofetch --noart`(windows) or `neofetch -- stdout`(macos&linux)**

# Operating system & way of installation

- Fedora 32 x86_64
- Python 3.8.6
- pip 19.3.1 from /usr/lib/python3.8/site-packages/pip (python 3.8)
- Installed via `pip3 install fetchcord --user`

# Error/issue

Can't run Fetchcord

# Other notes(optional)

**Other notes about the error/issue**

**Comment by rdlmda** [comment]
Any idea for the possible cause, or how can I start troubleshooting?

**Comment by BlivionIaG** [comment]
right, that one i don't know where its coming from, i need to hurry for releasing 2.7.0, that release is better to observe connecting stuff.

**Comment by BlivionIaG** [comment]
Hi, do you still have the same problem with the latest release ? I'm closing this ticket if I don't have any update in a week or two.

**Comment by rdlmda** [comment]
Let me test

**Comment by rdlmda** [comment]
Still have the same problem, apparently, although the output changed slightly:

```
Traceback (most recent call last):
  File "/home/ruda/.local/bin/fetchcord", line 8, in <module>
    sys.exit(main())
  File "/home/ruda/.local/lib/python3.8/site-packages/fetch_cord/__main__.py", line 100, in main
    run.run_loop(computer)
  File "/home/ruda/.local/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 61, in run_loop
    self.try_connect(self.loops_indexes[i])
  File "/home/ruda/.local/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 76, in try_connect
    self.rpcs[key].connect()
  File "/home/ruda/.local/lib/python3.8/site-packages/pypresence/presence.py", line 41, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ruda/.local/lib/python3.8/site-packages/pypresence/baseclient.py", line 121, in handshake
    self.sock_reader, self.sock_writer = await asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
  File "/usr/lib64/python3.8/asyncio/streams.py", line 111, in open_unix_connection
    transport, _ = await loop.create_unix_connection(
  File "/usr/lib64/python3.8/asyncio/unix_events.py", line 244, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/lib64/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/lib64/python3.8/asyncio/selector_events.py", line 501, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
```
