### ISSUE TITLE
Motherboard not supported

### ISSUE THREAD

**Issue by grandmasterethel** [MrPotatoBobx/FetchCord#127]
# Debug info

```
~ >>> fetchcord --debug                                                        
[KeyError]: 'Font:'[KeyError]: 'Font:'[KeyError]: 'Host:'
----run_rpc----

uptime in epoch: 1610124960.0
cpuid: 740614258177605642
cpuappid: 741152732756312125
termappid: 741328861115056160
[KeyError]: 'Host:'
1521 (pacman), 14 (snap) 
----out.py----

----DE/WM----
deid: GNOME
wmid: Mutter
wmline item 0: Mutter 

----TERMINAL----

[KeyError]: 'Font:'
fontline: Font: N/A
termid: 741328861115056160
termline item 0: gnome-terminal 
themeline: Matcha-dark-sea 
Adwaita-maia-dark [GTK2/3] 
[KeyError]: 'Host:'

----GPU INFO----

gpuinfo: AMD Radeon RX 5700 XT
gpuvendor: amd

----CPU INFO----

cpuvendor: amd
cpumodel: Ryzen 5
cpuinfo: AMD Ryzen 5 2600 (12) @ 3.400GHz
cpuline item 0: AMD Ryzen 5 2600 (12) @ 3.400GHz
memline: 2402MiB / 15999MiB 

----OS INFO----

sysosline: Manjaro Linux x86_64 
sysosid: 740614258177605642
[KeyError]: 'Disk'
diskline: Disk N/A
packagesline item 0: 1521 (pacman), 14 (snap) 

----testing.py----
----DE/WM----

deid: GNOME
wmid: Mutter

----TERMINAL/SHELL----

termid: 741328861115056160
shellid: zsh

----HOST INFO----

[KeyError]: 'Host:'
[KeyError]: 'Host:'
hostid: 742887089179197462

----GPU INFO----

gpuvendor: amd

----CPU INFO----

cpumodel: Ryzen 5

('DEFAULT', <Section: DEFAULT>)
('cycle_0', <Section: cycle_0>)
('cycle_1', <Section: cycle_1>)
('cycle_2', <Section: cycle_2>)
('cycle_3', <Section: cycle_3>)
[KeyError]: 'Host:'
Unknown motherboard, contact us on github to resolve this.
{}
cycle0 not in : True
try_connect(key="cycle0") on <pypresence.presence.Presence object at 0x7fd52aa00bb0>
Traceback (most recent call last):
  File "/usr/bin/fetchcord", line 33, in <module>
    sys.exit(load_entry_point('FetchCord==2.7.0', 'console_scripts', 'fetchcord')())
  File "/usr/lib/python3.9/site-packages/fetch_cord/__main__.py", line 100, in main
    run.run_loop(computer)
  File "/usr/lib/python3.9/site-packages/fetch_cord/run_rpc.py", line 61, in run_loop
    self.try_connect(self.loops_indexes[i])
  File "/usr/lib/python3.9/site-packages/fetch_cord/run_rpc.py", line 76, in try_connect
    self.rpcs[key].connect()
  File "/usr/lib/python3.9/site-packages/pypresence/presence.py", line 41, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/python3.9/site-packages/pypresence/baseclient.py", line 121, in handshake
    self.sock_reader, self.sock_writer = await asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
  File "/usr/lib/python3.9/asyncio/streams.py", line 111, in open_unix_connection
    transport, _ = await loop.create_unix_connection(
  File "/usr/lib/python3.9/asyncio/unix_events.py", line 244, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 507, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
```

NeoFetch:

```
OS: Manjaro Linux x86_64 
Kernel: 5.10.2-2-MANJARO 
Uptime: 13 mins 
Packages: 1521 (pacman), 14 (snap) 
Shell: zsh 5.8 
Resolution: 2560x1440, 1920x1080 
DE: GNOME 3.38.2 
WM: Mutter 
WM Theme: Matcha-dark-sea 
Theme: Adwaita-maia-dark [GTK2/3] 
Icons: Papirus-Dark-Maia [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 5 2600 (12) @ 3.400GHz 
GPU: AMD ATI Radeon RX 5600 OEM/5600 XT / 5700/5 
Memory: 2558MiB / 15999MiB 
```

# Requested item

Motherboard support for ASUS ROG STRIX B450-F

# Other notes

Thanks for your hard work :)

**Comment by MrPotatoBobx** [comment]
Man, this motherboard thing is becoming dumb, might have to remove the feature, there's too many motherboards to support

**Comment by grandmasterethel** [comment]
Yep. If you could remove that check entirely, I'd be a happy bunny.
Of all the things I'd want to display, my mobo is pretty low on the list.

**Comment by BlivionIaG** [comment]
I have an idea for the mobo system, but maybe we could just disable by default the mobo detection thing and let the user use it with an argument.
