### ISSUE TITLE
ModuleNotFoundError fetch_cord.computer

### ISSUE THREAD

**Issue by h05hardman** [MrPotatoBobx/FetchCord#144]
# Installed fetchcord

**From AUR**

# Operating system

**Manjaro Linux x86_64, Kernel 5.9.16-1-MANJARO**

# The Bug

**Not 100% sure if it's either an install issue or an bag report, but now I've chosen this because it is the first time I tried to use fetchcord.**
**I installed it with pamac from AUR, and if I run `fetchcord`, I get:**

# The Error Message

```
Traceback (most recent call last):
  File "/usr/bin/fetchcord", line 33, in <module>
    sys.exit(load_entry_point('FetchCord==2.7.2', 'console_scripts', 'fetchcord')())
  File "/usr/bin/fetchcord", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/fetch_cord/__main__.py", line 6, in <module>
    from .run_rpc import Run_rpc
  File "/usr/lib/python3.9/site-packages/fetch_cord/run_rpc.py", line 11, in <module>
    from .computer.Computer import Computer
ModuleNotFoundError: No module named 'fetch_cord.computer'
```

**Comment by h4ckerle** [comment]
See also #143

**Comment by BlivionIaG** [comment]
It should be fine now, I'm closing this.
