### ISSUE TITLE
cant launch fetchcord

### ISSUE THREAD

**Issue by tugusnr** [MrPotatoBobx/FetchCord#148]
# How you tried to install fetchcord
PIP because snap doesnt work
**This can be AUR, Github, or pip.**

# Operating system
Kali Linux
**Your OS goes here.**

# Other notes
When i type fetchcord this error appears:
[KeyError]: 'Font:'[KeyError]: 'Font:'('DEFAULT', <Section: DEFAULT>)
('cycle_0', <Section: cycle_0>)
('cycle_1', <Section: cycle_1>)
('cycle_2', <Section: cycle_2>)
('cycle_3', <Section: cycle_3>)
Unknown motherboard, contact us on github to resolve this.
Traceback (most recent call last):
  File "/usr/local/bin/fetchcord", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/fetch_cord/__main__.py", line 117, in main
    run.run_loop(computer)
  File "/usr/local/lib/python3.9/dist-packages/fetch_cord/run_rpc.py", line 63, in run_loop
    self.try_connect(self.loops_indexes[i])
  File "/usr/local/lib/python3.9/dist-packages/fetch_cord/run_rpc.py", line 78, in try_connect
    self.rpcs[key].connect()
  File "/usr/local/lib/python3.9/dist-packages/pypresence/presence.py", line 43, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/pypresence/baseclient.py", line 128, in handshake
    self.sock_reader, self.sock_writer = await asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
  File "/usr/lib/python3.9/asyncio/streams.py", line 111, in open_unix_connection
    transport, _ = await loop.create_unix_connection(
  File "/usr/lib/python3.9/asyncio/unix_events.py", line 244, in create_unix_connection
    await self.sock_connect(sock, path)[KeyError]: 'Font:'[KeyError]: 'Font:'('DEFAULT', <Section: DEFAULT>)
('cycle_0', <Section: cycle_0>)
('cycle_1', <Section: cycle_1>)
('cycle_2', <Section: cycle_2>)
('cycle_3', <Section: cycle_3>)
Unknown motherboard, contact us on github to resolve this.
Traceback (most recent call last):
  File "/usr/local/bin/fetchcord", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/fetch_cord/__main__.py", line 117, in main
    run.run_loop(computer)
  File "/usr/local/lib/python3.9/dist-packages/fetch_cord/run_rpc.py", line 63, in run_loop
    self.try_connect(self.loops_indexes[i])
  File "/usr/local/lib/python3.9/dist-packages/fetch_cord/run_rpc.py", line 78, in try_connect
    self.rpcs[key].connect()
  File "/usr/local/lib/python3.9/dist-packages/pypresence/presence.py", line 43, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/pypresence/baseclient.py", line 128, in handshake
    self.sock_reader, self.sock_writer = await asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
  File "/usr/lib/python3.9/asyncio/streams.py", line 111, in open_unix_connection
    transport, _ = await loop.create_unix_connection(
  File "/usr/lib/python3.9/asyncio/unix_events.py", line 244, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 507, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 507, in _sock_connect
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 507, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 507, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
**Other notes about install error/issue.**
im new to linux so sorry

**Comment by BlivionIaG** [comment]
Sorry for the late reply, thats quite some weird set of errors, can you join the discord so we can see the error in detail ? Also for now snap wont work since i lack one access to add it.
