### ISSUE TITLE
Program crashes on launch with FileNotFoundError

### ISSUE THREAD

**Issue by Slips-PC** [MrPotatoBobx/FetchCord#161]
# Debug info
```

slips@sliPC 
----------- 
OS: Arch Linux x86_64 
Host: Satellite P755 PSAY1U-03W027 
Kernel: 5.13.6-arch1-1 
Uptime: 8 mins 
Packages: 1259 (pacman) 
Shell: zsh 5.8 
Resolution: 1366x768 
WM: dwm 
Theme: Raleigh [GTK2/3] 
Icons: breeze [GTK2/3] 
Terminal: kitty 
CPU: Intel i7-2670QM (8) @ 3.100GHz 
GPU: Intel 2nd Generation Core Processor Family 
Memory: 1127MiB / 5844MiB 
Battery1: 63% [Discharging] 
Disk (/): 153G / 926G (18%)
[KeyError]: 'Font:'[KeyError]: 'Font:'----run_rpc----

uptime in epoch: 1627771343.0
cpuid: 740476198437650473
cpuappid: 741100300219187335
termappid: 741285676250824725
Unknown motherboard, contact us on github to resolve this.
hostappid: 742887089179197462
1259 (pacman) 
----out.py----

----DE/WM----
[KeyError]: 'DE:'
deid: n/a
wmid: dwm
wmline item 0: dwm 

----TERMINAL----

[KeyError]: 'Font:'
fontline: Font: N/A
termid: 741285676250824725
termline item 0: kitty 
themeline: Raleigh [GTK2/3] 

----HOST INFO----

hostline: Satellite P755 PSAY1U-03W027 
batteryline:  63% [Discharging] 
resline: 1366x768 

----GPU INFO----

gpuinfo: Intel 2nd Generation Core Processor Family
gpuvendor: intel

----CPU INFO----

cpuvendor: intel
cpumodel: Intel i7
cpuinfo: Intel i7-2670QM (8) @ 3.100GHz
cpuline item 0: Intel i7-2670QM (8) @ 3.100GHz
memline: 1127MiB / 5844MiB 

----OS INFO----

sysosline: Arch Linux x86_64 
sysosid: 740476198437650473
diskline: /): 153G / 926G (18%)
packagesline item 0: 1259 (pacman) 

----testing.py----
----DE/WM----

[KeyError]: 'DE:'
deid: n/a
wmid: dwm

----TERMINAL/SHELL----

termid: 741285676250824725
shellid: zsh

----HOST INFO----

hostid: 742887089179197462

----GPU INFO----

gpuvendor: intel

----CPU INFO----

cpumodel: Intel i7

```

# Operating system & way of installation

Arch Linux, fetchcord currently installed via pip3, although issue also occurs on AUR version

# Error/issue
This error occurs every time the program is run.

('DEFAULT', <Section: DEFAULT>)
('cycle_0', <Section: cycle_0>)
('cycle_1', <Section: cycle_1>)
('cycle_2', <Section: cycle_2>)
('cycle_3', <Section: cycle_3>)
Unknown motherboard, contact us on github to resolve this.
{}
cycle0 not in : True
try_connect(key="cycle0") on <pypresence.presence.Presence object at 0x7f0e63b61610>
Traceback (most recent call last):
  File "/home/slips/.local/bin/fetchcord", line 8, in <module>
    sys.exit(main())
  File "/home/slips/.local/lib/python3.9/site-packages/fetch_cord/__main__.py", line 117, in main
    run.run_loop(computer)
  File "/home/slips/.local/lib/python3.9/site-packages/fetch_cord/run_rpc.py", line 63, in run_loop
    self.try_connect(self.loops_indexes[i])
  File "/home/slips/.local/lib/python3.9/site-packages/fetch_cord/run_rpc.py", line 78, in try_connect
    self.rpcs[key].connect()
  File "/usr/lib/python3.9/site-packages/pypresence/presence.py", line 43, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/python3.9/site-packages/pypresence/baseclient.py", line 128, in handshake
    self.sock_reader, self.sock_writer = await asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
  File "/usr/lib/python3.9/asyncio/streams.py", line 111, in open_unix_connection
    transport, _ = await loop.create_unix_connection(
  File "/usr/lib/python3.9/asyncio/unix_events.py", line 244, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 507, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

# Other notes(optional)

I believe this to possibly be an issue with pypresence, since i have similar issues with other pypresence-based RPC programs.

**Comment by Slips-PC** [comment]
It is also worth noting that, upon inspection, all of these files *do* exist.
```
dir /usr/lib/python3.9/site-packages/pypresence
__init__.py  baseclient.py  exceptions.py  presence.py
__pycache__  client.py	   payloads.py    utils.py
```

```
dir /usr/lib/python3.9/site-packages/fetch_cord 
Cycle.py     __main__.py  computer	     cycles.py    run_command.py
Logger.py    __pycache__  config.py	     debugger.py  run_rpc.py
__init__.py  args.py	 config_schema.json  resources    update.py
```

```
dir /usr/lib/python3.9/asyncio/                
__init__.py	   constants.py       log.py		  staggered.py   unix_events.py
__main__.py	   coroutines.py      proactor_events.py  streams.py	 windows_events.py
__pycache__	   events.py	      protocols.py	  subprocess.py  windows_utils.py
base_events.py	   exceptions.py      queues.py	  tasks.py
base_futures.py     format_helpers.py  runners.py	  threads.py
base_subprocess.py  futures.py	      selector_events.py  transports.py
base_tasks.py	   locks.py	      sslproto.py	  trsock.py
```

**Comment by BlivionIaG** [comment]
Hello, I have a question, was Discord running when it crashed ?
