### ISSUE TITLE
Correct readme: Install and uninstall commands must be run with sudo

### ISSUE THREAD

**Issue by Adora16** [MrPotatoBobx/FetchCord#22]
If I run `pip3 uninstall fetchcord`, I get the following error:

```python3
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 788, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/usr/lib/python3.8/site-packages/FetchCord-0.1-py3.8.egg-info' -> '/tmp/pip-uninstall-hl2ccpix'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/uninstall.py", line 85, in run
    uninstall_pathset = req.uninstall(
  File "/usr/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 676, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/usr/lib/python3.8/site-packages/pip/_internal/req/req_uninstall.py", line 394, in remove
    moved.stash(path)
  File "/usr/lib/python3.8/site-packages/pip/_internal/req/req_uninstall.py", line 283, in stash
    renames(path, new_path)
  File "/usr/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 349, in renames
    shutil.move(old, new)
  File "/usr/lib/python3.8/shutil.py", line 800, in move
    rmtree(src)
  File "/usr/lib/python3.8/shutil.py", line 715, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.8/shutil.py", line 672, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.8/shutil.py", line 670, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'dependency_links.txt'
```
However, running the command with sudo works just fine. Same with installing. If I run `pip3 install fetchcord`, I get this message.
```python3
Defaulting to user installation because normal site-packages is not writeable
Collecting fetchcord
  Downloading FetchCord-2.0-py3-none-any.whl (15 kB)
Collecting pypresence
  Downloading pypresence-4.0.0.tar.gz (9.7 kB)
Building wheels for collected packages: pypresence
  Building wheel for pypresence (setup.py) ... done
  Created wheel for pypresence: filename=pypresence-4.0.0-py2.py3-none-any.whl size=10496 sha256=73e56e1092507f4b250cdb69672ae2808fd73ad8317adaf2981426dbb429077a
  Stored in directory: /home/athalia/.cache/pip/wheels/e5/05/c3/c9dc08bbd41a3c1fe94edf176312edeff285888e8c06c7328e
Successfully built pypresence
Installing collected packages: pypresence, fetchcord
Successfully installed fetchcord-2.0 pypresence-4.0.0
```
Upon running `fetchcord` I get this.
```python3
Unknown GPU, contact me on github to resolve this.(Keyerror)
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/athalia/.local/lib/python3.8/site-packages/fetch_cord/run-rpc.py", line 13, in <module>
    uptime = testing.uptime
NameError: name 'testing' is not defined
```
Then running `sudo pip3 uninstall fetchcord` gives me `WARNING: Skipping fetchcord as it is not installed.`

**Comment by MrPotatoBobx** [comment]
it works perfectly fine on ubuntu and openSUSE tumbleweed.

**Comment by MrPotatoBobx** [comment]
that line was also removed a while ago(testing.uptime)

**Comment by MrPotatoBobx** [comment]
works fine now
