### ISSUE TITLE
Fetchcord pip3 module fails with error

### ISSUE THREAD

**Issue by Adora16** [MrPotatoBobx/FetchCord#23]
When running `fetchcord`, I get the following error.
```python3
Unknown GPU, contact me on github to resolve this.(Keyerror)
Connecting
RPC connection successful.
Traceback (most recent call last):
  File "/home/athalia/.local/bin/fetchcord", line 8, in <module>
    sys.exit(main())
  File "/home/athalia/.local/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 24, in main
    loonix()
  File "/home/athalia/.local/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 139, in loonix
    cycle1()
  File "/home/athalia/.local/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 82, in cycle1
    RPC.update(state=cpuline[0], 
  File "/home/athalia/.local/lib/python3.8/site-packages/pypresence/presence.py", line 32, in update
    return self.loop.run_until_complete(self.read_output())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/athalia/.local/lib/python3.8/site-packages/pypresence/baseclient.py", line 105, in read_output
    raise ServerError(payload["data"]["message"])
pypresence.exceptions.ServerError: Child "activity" fails because child "details" fails because "details" is not allowed to be empty
```

**Comment by Hyper-KVM** [comment]
can you show the output with `--debug`?

**Comment by Adora16** [comment]
Different error now upon running `fetchcord`.
```python
Traceback (most recent call last):
  File "/home/athalia/.local/bin/fetchcord", line 5, in <module>
    from fetch_cord.run_rpc import main
  File "/home/athalia/.local/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 9, in <module>
    from fetch_cord.testing import uptime, gpuid, desktopid, appid, cpuappid, termappid
  File "/home/athalia/.local/lib/python3.8/site-packages/fetch_cord/testing.py", line 6, in <module>
    from fetch_cord.out import wmid, deid, termid, shellid, cpumodel, cpuvendor, gpuvendor, sysosid
  File "/home/athalia/.local/lib/python3.8/site-packages/fetch_cord/out.py", line 135, in <module>
    gpuvendor += amdgpuline[0].split()[1]
IndexError: list index out of range
```
`fetchcord --debug` gives the same output.

**Comment by Hyper-KVM** [comment]
I see, well you'll have to wait for @MrPotatoBobx to update the pip package or clone master and install manually as I fixed this issue.

**Comment by MrPotatoBobx** [comment]
pip package updated.

**Comment by MrPotatoBobx** [comment]
`pip3 install --upgrade fetchcord`
