### ISSUE TITLE
Error when running before starting Discord

### ISSUE THREAD

**Issue by Adora16** [MrPotatoBobx/FetchCord#24]
If I run `fetchcord` when Discord isn't running, I get the following error.
```python
Traceback (most recent call last):
  File "/home/athalia/.local/bin/fetchcord", line 8, in <module>
    sys.exit(main())
  File "/home/athalia/.local/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 24, in main
    loonix()
  File "/home/athalia/.local/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 137, in loonix
    cycle0()
  File "/home/athalia/.local/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 61, in cycle0
    RPC.connect()
  File "/home/athalia/.local/lib/python3.8/site-packages/pypresence/presence.py", line 41, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/athalia/.local/lib/python3.8/site-packages/pypresence/baseclient.py", line 121, in handshake
    self.sock_reader, self.sock_writer = await asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
  File "/usr/lib/python3.8/asyncio/streams.py", line 111, in open_unix_connection
    transport, _ = await loop.create_unix_connection(
  File "/usr/lib/python3.8/asyncio/unix_events.py", line 244, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 494, in sock_connect
    return await fut
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 499, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by MrPotatoBobx** [comment]
that means it cant connect
