### ISSUE TITLE
Cannot import name 'hostappid'

### ISSUE THREAD

**Issue by alexavil** [MrPotatoBobx/FetchCord#56]
After doing `fetchcord --update` (as the distro I'm using was added) and trying to launch it, I get this and it won't launch:
```
Traceback (most recent call last):
  File "/home/alex/.local/bin/fetchcord", line 7, in <module>
    from fetch_cord.run_rpc import main
  File "/home/alex/.local/lib/python3.6/site-packages/fetch_cord/run_rpc.py", line 12, in <module>
    from fetch_cord.testing import desktopid, termappid, hostappid
ImportError: cannot import name 'hostappid'
```

**Comment by Hyper-KVM** [comment]
commit: 60016d33f535ae03b8fd8db4d169c178b8567ec3 should fix that issue, please try doing  --update again.

**Comment by alexavil** [comment]
It worked, thanks.
