### ISSUE TITLE
Error on Archlinux

### ISSUE THREAD

**Issue by ShayBox** [MrPotatoBobx/FetchCord#67]
```
Traceback (most recent call last):
  File "/usr/bin/fetchcord", line 33, in <module>
    sys.exit(load_entry_point('FetchCord==2.5.2', 'console_scripts', 'fetchcord')())
  File "/usr/bin/fetchcord", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 10, in <module>
    from fetch_cord.testing import gpuid, cpuappid, appid
  File "/usr/lib/python3.8/site-packages/fetch_cord/testing.py", line 49, in <module>
    import fetch_cord.ressources as ressources
ModuleNotFoundError: No module named 'fetch_cord.ressources'
```

**Comment by Hyper-KVM** [comment]
Should be fixed now, try either the pip or AUR package.

**Comment by ShayBox** [comment]
```
Unsupported Terminal. contact us on github to resolve this.(Keyerror)
Unknown Host, contact us on github to resolve this.(Keyerror)
Connecting
RPC Connection Successful.
```

**Comment by Hyper-KVM** [comment]
looks like it's working fine, closing.

**Comment by ShayBox** [comment]
Unsupported terminal and unknown host, and it's not setting the status
