### ISSUE TITLE
Reopening Discord leads to unknown host

### ISSUE THREAD

**Issue by Adora16** [MrPotatoBobx/FetchCord#69]
I closed and reopened Discord, and Fetchcord said `RPC connection refused (is Discord open?); trying again in 30 seconds`. Upon reopening Discord, it displayed Unknown Host on Discord Rich Presense.

**Comment by Hyper-KVM** [comment]
can you do --debug for both first and following times opening discord?

**Comment by Adora16** [comment]
When I first open Discord I get this.
```python
----out.py----

----DE/WM----
deid: GNOME
wmid: Mutter
wmline item 0: WM: Mutter 

----TERMINAL----

fontline: Terminal Font: N/A
Font: N/A
termid: gnome-terminal
termline item 0: Terminal: gnome-terminal 
themeline: WM Theme: Matcha-dark-sea 
Theme: Matcha-dark-sea [GTK2/3] 

----GPU INFO----

amdgpurenderlist: []
nvidiagpuline: []
intelgpuline: ['GPU: Intel HD Graphics ']
gpuinfo: GPU: Intel HD Graphics 
gpuvendor: Intel

----CPU INFO----

cpuvendor: Intel
cpumodel: Intel i5
cpuinfo: CPU: Intel i5-3470 (4) @ 3.600GHz
cpuline item 0: CPU: Intel i5-3470 (4) @ 3.600GHz 
memline: ['Memory: 11624MiB / 15898MiB']

----OS INFO----

sysosline: ['OS: Manjaro Linux x86_64 ']
sysosid: Manjaro
packagesline item 0: Packages: 1154 (pacman) 
Unknown Host, contact us on github to resolve this.(Keyerror)

----testing.py----
----DE/WM----

deid: GNOME
wmid: Mutter

----TERMINAL/SHELL----

termid: gnome-terminal
shellid: zsh

----HOST INFO----

hostid: 

----GPU INFO----

gpuvendor: Intel

----CPU INFO----

cpumodel: Intel i5

Connecting
----run_rpc----

uptime in epoch: 1598363247.0
cpuid: 740614258177605642
cpuappid: 741099939198926920
termappid: 741328861115056160
hostappid: 742887089179197462
Packages: 1154 (pacman) 
RPC Connection Successful.
cycle 0
appid: 740614258177605642
cycle 1
appid: 741099939198926920
```
After closing and reopening Discord, I get this.
```python
Traceback (most recent call last):
  File "/usr/bin/fetchcord", line 33, in <module>
    sys.exit(load_entry_point('FetchCord==2.5.4', 'console_scripts', 'fetchcord')())
  File "/usr/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 44, in main
    loonix(memline, packagesline, i, cpuinfo, batteryline, diskline)
  File "/usr/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 375, in loonix
    cycle3(batteryline)
  File "/usr/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 219, in cycle3
    rpc_tryconnect(RPC)
  File "/usr/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 68, in rpc_tryconnect
    RPC.connect()
  File "/usr/lib/python3.8/site-packages/pypresence/presence.py", line 40, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/site-packages/pypresence/baseclient.py", line 113, in handshake
    code, length = struct.unpack('<ii', data[:8])
struct.error: unpack requires a buffer of 8 bytes
```

**Comment by Hyper-KVM** [comment]
try now with this commit: https://github.com/MrPotatoBobx/FetchCord/commit/0f630da4c79975e05dbfb1503819125c367bcaec
