### ISSUE TITLE
Errors on macOS 10.14

### ISSUE THREAD

**Issue by thebitstick** [MrPotatoBobx/FetchCord#79]
```
user@host ~ [1]> fetchcord --debug
----out.py----

----DE/WM----
deid: Aqua
wmid: Rectangle
wmline item 0: WM: Rectangle

----TERMINAL----

termfontline: Font: Monaco 12
termid: iTerm2
termline item 0: Terminal: iTerm2
themeline: ['N/A']

----GPU INFO----

amdgpurenderlist: []
nvidiagpuline: []
intelgpuline: []
gpuinfo:
gpuvendor:

----CPU INFO----

cpuvendor: AMD
cpumodel: Ryzen 5
cpuline item 0: CPU: AMD Ryzen 5 3600
memline: ['Memory: 12112MiB / 32768MiB']

----OS INFO----

sysosline: ['OS: macOS Mojave 10.14.6 18G103 x86_64 ', 'Host: Hackintosh (SMBIOS: iMacPro1,1) ']
sysosid: macOS
packagesline item 0: Packages: 122 (brew)
Unsupported Terminal. contact us on github to resolve this.(Keyerror)
Unsupported Distro, contact us on the GitHub page to resolve this.(keyerror)
Unknown GPU, contact us on github to resolve this.(Keyerror)

----testing.py----
----DE/WM----

deid: Aqua
wmid: Rectangle

----TERMINAL/SHELL----

termid: iTerm2
shellid: fish

----HOST INFO----

hostid:

----GPU INFO----

gpuvendor:

----CPU INFO----

cpumodel: Ryzen 5

Traceback (most recent call last):
  File "/usr/local/bin/fetchcord", line 5, in <module>
    from fetch_cord.run_rpc import main
  File "/usr/local/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 13, in <module>
    from fetch_cord.testing import desktopid, termappid, hostappid
ImportError: cannot import name 'desktopid' from 'fetch_cord.testing' (/usr/local/lib/python3.8/site-packages/fetch_cord/testing.py)
```

Important bit:
```
Unsupported Terminal. contact us on github to resolve this.(Keyerror)
Unsupported Distro, contact us on the GitHub page to resolve this.(keyerror)
Unknown GPU, contact us on github to resolve this.(Keyerror)
```

**Comment by BlivionIaG** [comment]
Hello, is this still not working ? I'm closing this in a week or 2 if i don't have a response.

**Comment by thebitstick** [comment]
It doesn't crash anymore, but I still get plenty of errors.
I am now on Big Sur on an M1 Mac Mini.

```
user@host ~ % fetchcord --debug
----out.py----

----DE/WM----
deid: Aqua
wmid: Rectangle
wmline item 0: ['WM: Rectangle ']

----TERMINAL----

fontline: ['Terminal Font: Monaco 12 ']
termid: iTerm2
termline item 0: Terminal: iTerm2
themeline: Theme: N/A

----HOST INFO----

hostline: Host: Macmini9,1
batteryline: Battery: N/A
resline: Resolution: 2560x1080, 1680x1050

----GPU INFO----

gpuinfo: GPU: N/A
gpuvendor: Apple

----CPU INFO----

cpuvendor: VirtualApple
cpumodel: N/A
cpuinfo: CPU: VirtualApple  @ 2.50GHz processor
cpuline item 0: ['CPU: VirtualApple (8) @ 2.50GHz processor ']
memline: Memory: 2159MiB / 16384MiB

----OS INFO----

sysosline: OS: macOS Big Sur 11.0.1 20B29 x86_64
sysosid: macOS
diskline: Disk: N/A
packagesline item 0: Packages: 111 (brew)
Unsupported MacOS version
Unknown GPU, contact us on github to resolve this.
Unknown DE/WM, contact us on github to resolve this.
Unknown Host, contact us on github to resolve this.(Keyerror)
Unsupported Terminal. contact us on github to resolve this.(Keyerror)
Unsupported Distro, contact us on the GitHub page to resolve this.(keyerror)

----testing.py----
----DE/WM----

deid: Aqua
wmid: Rectangle

----TERMINAL/SHELL----

termid: iTerm2
shellid: zsh

----HOST INFO----

hostid: o

----GPU INFO----

gpuvendor: Apple

----CPU INFO----

cpumodel: N/A

Connecting
----run_rpc----

uptime in epoch: 1606110848.0
cpuid: 742993278143692821
cpuappid: 742887089179197462
termappid: 745691250186911796
hostappid: 742887089179197462
Packages: 111 (brew)
('DEFAULT', <Section: DEFAULT>)
('cycle_0', <Section: cycle_0>)
('cycle_1', <Section: cycle_1>)
('cycle_2', <Section: cycle_2>)
('cycle_3', <Section: cycle_3>)
RPC Connection Successful.
runmac
devicetype: desktop
product Macmini9,1

bigicon: bigslurp
ver: 11.0.1

uptime: 1606110848.0
client_id: 740822755376758944
cycle 1
appid: 742887089179197462
```

**Comment by BlivionIaG** [comment]
Nice, that's perfect I was wondering where i could find an M1 user, can i get the neofetch --stdout output ? You can join the discord for faster responses if you want.

**Comment by thebitstick** [comment]
On iTerm.app with fish shell (so running under Rosetta 2):
```
me@host
------------------
OS: macOS Big Sur 11.0.1 20B29 x86_64
Host: Macmini9,1
Kernel: 20.1.0
Uptime: 11 hours, 32 mins
Packages: 111 (brew)
Shell: zsh 5.8
Resolution: 2560x1080, 1680x1050
DE: Aqua
WM: Rectangle
Terminal: iTerm2
Terminal Font: Monaco 12
CPU: VirtualApple (8) @ 2.50GHz processor
GPU: Apple M1
Memory: 2183MiB / 16384MiB
```

On Terminal.app with zsh (so native ARM):
```
me@host 
------------------ 
OS: macOS Big Sur 11.0.1 20B29 arm64 
Host: Macmini9,1 
Kernel: 20.1.0 
Uptime: 11 hours, 33 mins 
Packages: 111 (brew) 
Shell: zsh 5.8 
Resolution: 2560x1080, 1680x1050 
DE: Aqua 
WM: Rectangle 
Terminal: Apple_Terminal 
Terminal Font: Monaco 
CPU: Apple processor 
GPU: Apple M1 
Memory: 2180MiB / 16384MiB
```

**Comment by BlivionIaG** [comment]
Thanks, i'll have to find some icons and add it for the next release

**Comment by MrPotatoBobx** [comment]
will add soon thanks for the patience
