### ISSUE TITLE
Crash after 5 minutes of using 

### ISSUE THREAD

**Issue by vesterlay** [MrPotatoBobx/FetchCord#80]
```
Traceback (most recent call last):
  File "/usr/bin/fetchcord", line 33, in <module>
    sys.exit(load_entry_point('FetchCord==2.5.4', 'console_scripts', 'fetchcord')())
  File "/usr/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 46, in main
    loonix(loop)
  File "/usr/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 337, in loonix
    cycle3()
  File "/usr/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 241, in cycle3
    loonix(loop)
UnboundLocalError: local variable 'loop' referenced before assignment

```

**Comment by Hyper-KVM** [comment]
I knew this would cause a problem dang it XD, I fixed it this with commit: 4bc44815545759e1567b9dbe3df6a5421dbe8c42

**Comment by vesterlay** [comment]
Latest update
```
Traceback (most recent call last):
  File "/usr/bin/fetchcord", line 33, in <module>
    sys.exit(load_entry_point('FetchCord==2.5.5', 'console_scripts', 'fetchcord')())
  File "/usr/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 46, in main
    loonix(loop)
  File "/usr/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 320, in loonix
    cycle3()
  File "/usr/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 222, in cycle3
    rpc_tryupdate(RPC,
  File "/usr/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 87, in rpc_tryupdate
    RPC.update(state=state, details=details, large_image=large_image,
  File "/usr/lib/python3.8/site-packages/pypresence/presence.py", line 32, in update
    return self.loop.run_until_complete(self.read_output())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/site-packages/pypresence/baseclient.py", line 86, in read_output
    raise ServerError(payload["data"]["message"])
pypresence.exceptions.ServerError: Child "activity" fails because child "assets" fails because child "large_text" fails because "large_text" length must be at least 2 characters long

```

**Comment by Hyper-KVM** [comment]
Should work fine now, try again

**Comment by vesterlay** [comment]
Seems alright, thanks for your work :)
