### ISSUE TITLE
error: name 'cpuinfo' is not defined on Arch Linux using AUR package

### ISSUE THREAD

**Issue by AAGaming00** [MrPotatoBobx/FetchCord#82]
This erorr does not happen when installed using pip.
Full error: 
```
aagaming@arches ~> fetchcord --debug
laptop: True
Traceback (most recent call last):
  File "/usr/bin/fetchcord", line 33, in <module>
    sys.exit(load_entry_point('FetchCord==2.5.5', 'console_scripts', 'fetchcord')())
  File "/usr/bin/fetchcord", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/fetch_cord/run_rpc.py", line 10, in <module>
    from fetch_cord.testing import gpuid, cpuappid, appid
  File "/usr/lib/python3.8/site-packages/fetch_cord/testing.py", line 5, in <module>
    from fetch_cord.out import cpumodel, cpuvendor, gpuvendor, sysosid
  File "/usr/lib/python3.8/site-packages/fetch_cord/out.py", line 302, in <module>
    diskline = check_diskline(diskline)
  File "/usr/lib/python3.8/site-packages/fetch_cord/checks.py", line 323, in check_diskline
    diskline = cpuinfo
NameError: name 'cpuinfo' is not defined
```

**Comment by Hyper-KVM** [comment]
Should be fixed now, try again after updating.

**Comment by BlivionIaG** [comment]
So, since there is no feedback, and it should be fixed, i'm closing it
