### ISSUE TITLE
ModuleNotFoundError: No module named 'fetch_cord.debugger'

### ISSUE THREAD

**Issue by alexavil** [MrPotatoBobx/FetchCord#92]
# Debug info
```
OS: Zorin OS 15.3 x86_64 
Host: 350V5C/350V5X/350V4C/350V4X/351V5C/351V5X/351V4C/351V4X/3540VC/3540VX/3440VC/3440VX P03AAL.015.CP 
Kernel: 5.4.0-45-generic 
Uptime: 13 hours, 58 mins 
Packages: 2665 
Shell: bash 4.4.20 
Resolution: 1366x768 
DE: GNOME 3.30.2 
WM: GNOME Shell 
WM Theme: ZorinBlue-Dark 
Theme: ZorinBlue-Dark [GTK2/3] 
Icons: ZorinBlue-Dark [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-3210M (4) @ 3.100GHz 
GPU: Intel HD Graphics 4000 
Memory: 2551MiB / 3829MiB
```

# Operating system & way of installation

OS: Zorin OS 15.3 x86_64. Fetchcord was installed via `pip`

# Error/issue
Fetchcord won't start because of this error:

```
Traceback (most recent call last):
  File "/home/alex/.local/bin/fetchcord", line 7, in <module>
    from fetch_cord.run_rpc import main
  File "/home/alex/.local/lib/python3.6/site-packages/fetch_cord/run_rpc.py", line 9, in <module>
    from fetch_cord.testing import gpuid, appid, cpuappid
  File "/home/alex/.local/lib/python3.6/site-packages/fetch_cord/testing.py", line 6, in <module>
    from fetch_cord.debugger import test_debug
ModuleNotFoundError: No module named 'fetch_cord.debugger'

**Comment by BlivionIaG** [comment]
Hello, this error should not exist anymore, I'm thinking of closing this in a week or two if i don't have a response.

**Comment by MrPotatoBobx** [comment]
try fetchcord 2.7, reopen the issue if the issue still happens
